  <footer role="contentinfo">
    <p id="page_title">About Us</p>
    <p id="copyright">&#169; Group Khichuri</p>
    <p id="slogan">Stronger Together</p>
    <p>
      <a href="https://github.com/106160340/assignment1.git" target="_blank" rel="noopener noreferrer">View our
        GitHub Repository</a> |
      <a href="https://student-team-10026.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?epics=visible&atlOrigin=eyJpIjoiYmUyNTNlMjBmZDVkNGQ2MTk1NTg2Njk3YzMwYTQ2ZDUiLCJwIjoiaiJ9" target="_blank"
        rel="noopener noreferrer">Track Issues on Jira</a>
    </p>
  </footer>