<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial scale=1.0">
    <meta name="description" content="State University job ads">
    <meta name="keywords"
        content="University, jobs, research, digital, computer science, technology, position, IT, application, salary package">
    <meta name="author" content="State University HR team">
    <title>Khitchuri</title>
    <!-- reference to external CSS -->
    <link rel="stylesheet" type="text/css" href="styles/style.css">
    <!-- responsive design CSS -->
    <link href="styles/responsive.css" rel="stylesheet" media="screen and (max-width: 3840px)" />
</head>