<div class="heaader">
        <img src="images/logo.png" alt="State University logo" title="Logo" class="logo">
        <nav role="navigation">
            <ul id="nav_list">
            <li><a href="about.php">About</a></li><li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="index.php" aria-current="page">Home</a></li>
            </ul>
        </nav>
    </div>