    <div class="header" role="banner">
        <!-- Logo links back to home -->
        <a href="index.php" aria-label="Go to Home Page">
            <img src="images/logo.png" alt="State University Logo" title="Logo" class="logo">
        </a>
        <!-- Navigation bar with links to all pages -->
        <nav role="navigation">
            <ul>
                <li><a href="about.php"aria-current="page">About</a></li>
                <li><a href="apply.php" aria-current="page">Apply</a></li>
                <li><a href="jobs.php"aria-current="page">Jobs</a></li>
                <li><a href="index.php"aria-current="page">Home</a></li>
            </ul>
        </nav>
    </div>